# Generated by Django 5.0.2 on 2024-03-05 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='firstname',
            new_name='agnname',
        ),
        migrations.RemoveField(
            model_name='task',
            name='lastname',
        ),
    ]
