# Generated by Django 5.0.2 on 2024-03-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_firstname_task_agnname_remove_task_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='plot_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
