# Generated by Django 5.0.2 on 2024-03-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_plot_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='plot_name',
        ),
    ]
