# Generated by Django 5.0.2 on 2024-03-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_plot_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='voption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plotname', models.CharField(max_length=255)),
            ],
        ),
    ]
